config/routes.rb
Rails.application.routes.draw do
  resources :education_backgrounds

  resources :students

  resources :type_of_degrees

  resources :marital_statuses

  resources :genders

end

app/controllers/marital_statuses_controller.rb
class MaritalStatusesController < ApplicationController
  before_action :set_marital_status, only: [:show, :edit, :update, :destroy]

  # GET /marital_statuses
  # GET /marital_statuses.json
  def index
    @marital_statuses = MaritalStatus.all
  end

  # GET /marital_statuses/1
  # GET /marital_statuses/1.json
  def show
  end

  # GET /marital_statuses/new
  def new
    @marital_status = MaritalStatus.new
  end

  # GET /marital_statuses/1/edit
  def edit
  end

  # POST /marital_statuses
  # POST /marital_statuses.json
  def create
    @marital_status = MaritalStatus.new(marital_status_params)

    respond_to do |format|
      if @marital_status.save
        format.html { redirect_to @marital_status, notice: 'Marital status was successfully created.' }
        format.json { render :show, status: :created, location: @marital_status }
      else
        format.html { render :new }
        format.json { render json: @marital_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /marital_statuses/1
  # PATCH/PUT /marital_statuses/1.json
  def update
    respond_to do |format|
      if @marital_status.update(marital_status_params)
        format.html { redirect_to @marital_status, notice: 'Marital status was successfully updated.' }
        format.json { render :show, status: :ok, location: @marital_status }
      else
        format.html { render :edit }
        format.json { render json: @marital_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /marital_statuses/1
  # DELETE /marital_statuses/1.json
  def destroy
    @marital_status.destroy
    respond_to do |format|
      format.html { redirect_to marital_statuses_url, notice: 'Marital status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_marital_status
      @marital_status = MaritalStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marital_status_params
      params.require(:marital_status).permit(:name)
    end
end

app/helpers/marital_statuses_helper.rb
module MaritalStatusesHelper
end

app/views/marital_statuses/_form.html.erb
<%= form_for(@marital_status, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @marital_status.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@marital_status.errors.count, "error") %> prohibited this marital_status from being saved:</h4>

      <ul>
      <% @marital_status.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6">
    <div class="inline-form">
      <%= f.label :name, :class => "c-label" %>
      <%= f.text_field :name%>
    </div>
  </div>
<div class="col-md-12">
    <br>
      <%= f.submit :class => "btn btn-primary" %>
      <%= link_to marital_statuses_path, :class => 'btn btn-default' do %>
    <span class="fa fa-list-alt"></span>
    Back
  <% end %>
</div>
<% end %>

app/views/marital_statuses/edit.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="widget-area">
			<div class="wizard-form-h">
				<div id="wizard" class="swMain">
					<h2 class="StepTitle">
						<strong>Editing</strong> marital_status
					</h2>

					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/marital_statuses/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="widget-area">

     <div class="streaming-table">

      <span style="display: none;" id="found" class="label label-info"></span>
      <div class="heading">
        <strong>Listing</strong> marital_statuses
        <input name="search" id="st_search" class="st_search" placeholder="Search Here" type="text">
      </div>
      <div class="table-responsive">
        <table id="stream_table" class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
                            <th>Name</th>
                            <th></th>
            </tr>
          </thead>

          <tbody>
            <%= content_tag_for(:tr, @marital_statuses) do |marital_status| %>
                        <td><%= marital_status.name %></td>
                        <td><%= link_to '<i class="fa fa-book"></i>'.html_safe, marital_status, class: "btn btn-sm btn-default" %>
            <%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_marital_status_path(marital_status), class: "btn btn-sm btn-primary" %>
            <%= link_to '<i class="fa fa-remove (alias)"></i>'.html_safe, marital_status, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>  
    <div class="">
     <%= link_to new_marital_status_path, :class => 'btn btn-primary' do %>
        <span class="fa fa-plus"></span>
        New 
        <% end %>
    </div>
  </div></div>
</div>

app/views/marital_statuses/new.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="widget-area">
			<div class="wizard-form-h">
				<div id="wizard" class="swMain">
					<h2 class="StepTitle">
						<strong>New</strong> marital_status
					</h2>
			<%= render 'form' %>
		</div>
	</div>
</div>



  

app/views/marital_statuses/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="widget-area">
      <div class="wizard-form-h">
        <div id="wizard" class="swMain">


          <%= link_to marital_statuses_path, :class => 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
          <% end %>
          <%= link_to edit_marital_status_path(@marital_status), :class => 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Edit
          <% end %>
            <div class="heading">
        <strong>show</strong> marital_status
          marital_status

        <dl class="dl-horizontal">
          <dt>Name:</dt>
          <dd><%= @marital_status.name %></dd>

        </dl>

        </div>
      </div>
    </div>
  </div>
</div>