config/routes.rb
Rails.application.routes.draw do
  resources :education_backgrounds

  resources :students

  resources :type_of_degrees

  resources :marital_statuses

  resources :genders

end

app/models/type_of_degree.rb
class TypeOfDegree < ActiveRecord::Base
end

app/controllers/type_of_degrees_controller.rb
class TypeOfDegreesController < ApplicationController
  before_action :set_type_of_degree, only: [:show, :edit, :update, :destroy]

  # GET /type_of_degrees
  # GET /type_of_degrees.json
  def index
    @type_of_degrees = TypeOfDegree.all
  end

  # GET /type_of_degrees/1
  # GET /type_of_degrees/1.json
  def show
  end

  # GET /type_of_degrees/new
  def new
    @type_of_degree = TypeOfDegree.new
  end

  # GET /type_of_degrees/1/edit
  def edit
  end

  # POST /type_of_degrees
  # POST /type_of_degrees.json
  def create
    @type_of_degree = TypeOfDegree.new(type_of_degree_params)

    respond_to do |format|
      if @type_of_degree.save
        format.html { redirect_to @type_of_degree, notice: 'Type of degree was successfully created.' }
        format.json { render :show, status: :created, location: @type_of_degree }
      else
        format.html { render :new }
        format.json { render json: @type_of_degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /type_of_degrees/1
  # PATCH/PUT /type_of_degrees/1.json
  def update
    respond_to do |format|
      if @type_of_degree.update(type_of_degree_params)
        format.html { redirect_to @type_of_degree, notice: 'Type of degree was successfully updated.' }
        format.json { render :show, status: :ok, location: @type_of_degree }
      else
        format.html { render :edit }
        format.json { render json: @type_of_degree.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /type_of_degrees/1
  # DELETE /type_of_degrees/1.json
  def destroy
    @type_of_degree.destroy
    respond_to do |format|
      format.html { redirect_to type_of_degrees_url, notice: 'Type of degree was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_type_of_degree
      @type_of_degree = TypeOfDegree.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def type_of_degree_params
      params.require(:type_of_degree).permit(:name)
    end
end

app/helpers/type_of_degrees_helper.rb
module TypeOfDegreesHelper
end

app/views/type_of_degrees/_form.html.erb
<%= form_for(@type_of_degree, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @type_of_degree.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@type_of_degree.errors.count, "error") %> prohibited this type_of_degree from being saved:</h4>

      <ul>
      <% @type_of_degree.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6">
    <div class="inline-form">
      <%= f.label :name, :class => "c-label" %>
      <%= f.text_field :name%>
    </div>
  </div>
<div class="col-md-12">
    <br>
      <%= f.submit :class => "btn btn-primary" %>
      <%= link_to type_of_degrees_path, :class => 'btn btn-default' do %>
    <span class="fa fa-list-alt"></span>
    Back
  <% end %>
</div>
<% end %>

app/views/type_of_degrees/edit.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="widget-area">
			<div class="wizard-form-h">
				<div id="wizard" class="swMain">
					<h2 class="StepTitle">
						<strong>Editing</strong> type_of_degree
					</h2>

					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/type_of_degrees/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="widget-area">

     <div class="streaming-table">

      <span style="display: none;" id="found" class="label label-info"></span>
      <div class="heading">
        <strong>Listing</strong> type_of_degrees
        <input name="search" id="st_search" class="st_search" placeholder="Search Here" type="text">
      </div>
      <div class="table-responsive">
        <table id="stream_table" class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
                            <th>Name</th>
                            <th></th>
            </tr>
          </thead>

          <tbody>
            <%= content_tag_for(:tr, @type_of_degrees) do |type_of_degree| %>
                        <td><%= type_of_degree.name %></td>
                        <td><%= link_to '<i class="fa fa-book"></i>'.html_safe, type_of_degree, class: "btn btn-sm btn-default" %>
            <%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_type_of_degree_path(type_of_degree), class: "btn btn-sm btn-primary" %>
            <%= link_to '<i class="fa fa-remove (alias)"></i>'.html_safe, type_of_degree, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>  
    <div class="">
     <%= link_to new_type_of_degree_path, :class => 'btn btn-primary' do %>
        <span class="fa fa-plus"></span>
        New 
        <% end %>
    </div>
  </div></div>
</div>

app/views/type_of_degrees/new.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="widget-area">
			<div class="wizard-form-h">
				<div id="wizard" class="swMain">
					<h2 class="StepTitle">
						<strong>New</strong> type_of_degree
					</h2>
			<%= render 'form' %>
		</div>
	</div>
</div>



  

app/views/type_of_degrees/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="widget-area">
      <div class="wizard-form-h">
        <div id="wizard" class="swMain">


          <%= link_to type_of_degrees_path, :class => 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
          <% end %>
          <%= link_to edit_type_of_degree_path(@type_of_degree), :class => 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Edit
          <% end %>
            <div class="heading">
        <strong>show</strong> type_of_degree
          type_of_degree

        <dl class="dl-horizontal">
          <dt>Name:</dt>
          <dd><%= @type_of_degree.name %></dd>

        </dl>

        </div>
      </div>
    </div>
  </div>
</div>