config/routes.rb
Rails.application.routes.draw do
  resources :education_backgrounds

  resources :students

  resources :type_of_degrees

  resources :marital_statuses

  resources :genders

end

app/models/education_background.rb
class EducationBackground < ActiveRecord::Base
  belongs_to :type_of_degree
  belongs_to :student
end

app/controllers/education_backgrounds_controller.rb
class EducationBackgroundsController < ApplicationController
  before_action :set_education_background, only: [:show, :edit, :update, :destroy]

  # GET /education_backgrounds
  # GET /education_backgrounds.json
  def index
    @education_backgrounds = EducationBackground.all
  end

  # GET /education_backgrounds/1
  # GET /education_backgrounds/1.json
  def show
  end

  # GET /education_backgrounds/new
  def new
    @education_background = EducationBackground.new
  end

  # GET /education_backgrounds/1/edit
  def edit
  end

  # POST /education_backgrounds
  # POST /education_backgrounds.json
  def create
    @education_background = EducationBackground.new(education_background_params)

    respond_to do |format|
      if @education_background.save
        format.html { redirect_to @education_background, notice: 'Education background was successfully created.' }
        format.json { render :show, status: :created, location: @education_background }
      else
        format.html { render :new }
        format.json { render json: @education_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /education_backgrounds/1
  # PATCH/PUT /education_backgrounds/1.json
  def update
    respond_to do |format|
      if @education_background.update(education_background_params)
        format.html { redirect_to @education_background, notice: 'Education background was successfully updated.' }
        format.json { render :show, status: :ok, location: @education_background }
      else
        format.html { render :edit }
        format.json { render json: @education_background.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /education_backgrounds/1
  # DELETE /education_backgrounds/1.json
  def destroy
    @education_background.destroy
    respond_to do |format|
      format.html { redirect_to education_backgrounds_url, notice: 'Education background was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_education_background
      @education_background = EducationBackground.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def education_background_params
      params.require(:education_background).permit(:high_school, :english_program, :degree_program, :university, :graduate_school, :type_of_degree_id, :desired_major, :student_id)
    end
end

app/helpers/education_backgrounds_helper.rb
module EducationBackgroundsHelper
end

app/views/education_backgrounds/_form.html.erb
<%= form_for(@education_background, :html => { :class => "form-horizontal" }) do |f| %>
  <% if @education_background.errors.any? %>
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <h4><%= pluralize(@education_background.errors.count, "error") %> prohibited this education_background from being saved:</h4>

      <ul>
      <% @education_background.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="col-md-6">
    <div class="inline-form">
      <%= f.label :high_school, :class => "c-label" %>
      <%= f.text_area :high_school%>
    </div>
  </div>
  <div class="col-md-6">
    <div class="inline-form">
      <%= f.label :english_program, :class => "c-label" %>
      <%= f.text_area :english_program%>
    </div>
  </div>
  <div class="col-md-6">
    <div class="inline-form">
      <%= f.label :degree_program, :class => "c-label" %>
      <%= f.text_area :degree_program%>
    </div>
  </div>
  <div class="col-md-6">
    <div class="inline-form">
      <%= f.label :university, :class => "c-label" %>
      <%= f.text_area :university%>
    </div>
  </div>
  <div class="col-md-6">
    <div class="inline-form">
      <%= f.label :graduate_school, :class => "c-label" %>
      <%= f.text_area :graduate_school%>
    </div>
  </div>
  <div class="col-md-6">
    <div class="inline-form">
      <%= f.label :type_of_degree, :class => "c-label" %>
      <%= f.text_field :type_of_degree%>
    </div>
  </div>
  <div class="col-md-6">
    <div class="inline-form">
      <%= f.label :desired_major, :class => "c-label" %>
      <%= f.text_field :desired_major%>
    </div>
  </div>
<div class="col-md-12">
    <br>
      <%= f.submit :class => "btn btn-primary" %>
      <%= link_to education_backgrounds_path, :class => 'btn btn-default' do %>
    <span class="fa fa-list-alt"></span>
    Back
  <% end %>
</div>
<% end %>

app/views/education_backgrounds/edit.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="widget-area">
			<div class="wizard-form-h">
				<div id="wizard" class="swMain">
					<h2 class="StepTitle">
						<strong>Editing</strong> education_background
					</h2>

					<%= render 'form' %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/education_backgrounds/index.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="widget-area">

     <div class="streaming-table">

      <span style="display: none;" id="found" class="label label-info"></span>
      <div class="heading">
        <strong>Listing</strong> education_backgrounds
        <input name="search" id="st_search" class="st_search" placeholder="Search Here" type="text">
      </div>
      <div class="table-responsive">
        <table id="stream_table" class="table table-striped table-bordered table-hover">
          <thead>
            <tr>
                            <th>High school</th>
                            <th>English program</th>
                            <th>Degree program</th>
                            <th>University</th>
                            <th>Graduate school</th>
                            <th>Type of degree</th>
                            <th>Desired major</th>
                            <th>Student</th>
                            <th></th>
            </tr>
          </thead>

          <tbody>
            <%= content_tag_for(:tr, @education_backgrounds) do |education_background| %>
                        <td><%= education_background.high_school %></td>
                        <td><%= education_background.english_program %></td>
                        <td><%= education_background.degree_program %></td>
                        <td><%= education_background.university %></td>
                        <td><%= education_background.graduate_school %></td>
                        <td><%= education_background.type_of_degree %></td>
                        <td><%= education_background.desired_major %></td>
                        <td><%= education_background.student %></td>
                        <td><%= link_to '<i class="fa fa-book"></i>'.html_safe, education_background, class: "btn btn-sm btn-default" %>
            <%= link_to '<i class="fa fa-pencil-square-o"></i>'.html_safe, edit_education_background_path(education_background), class: "btn btn-sm btn-primary" %>
            <%= link_to '<i class="fa fa-remove (alias)"></i>'.html_safe, education_background, class: "btn btn-sm btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>  
    <div class="">
     <%= link_to new_education_background_path, :class => 'btn btn-primary' do %>
        <span class="fa fa-plus"></span>
        New 
        <% end %>
    </div>
  </div></div>
</div>

app/views/education_backgrounds/new.html.erb
<div class="row">
	<div class="col-md-12">
		<div class="widget-area">
			<div class="wizard-form-h">
				<div id="wizard" class="swMain">
					<h2 class="StepTitle">
						<strong>New</strong> education_background
					</h2>
			<%= render 'form' %>
		</div>
	</div>
</div>



  

app/views/education_backgrounds/show.html.erb
<div class="row">
  <div class="col-md-12">
    <div class="widget-area">
      <div class="wizard-form-h">
        <div id="wizard" class="swMain">


          <%= link_to education_backgrounds_path, :class => 'btn btn-default' do %>
          <span class="glyphicon glyphicon-list-alt"></span>
          Back
          <% end %>
          <%= link_to edit_education_background_path(@education_background), :class => 'btn btn-primary' do %>
          <span class="glyphicon glyphicon-pencil"></span>
          Edit
          <% end %>
            <div class="heading">
        <strong>show</strong> education_background
          education_background

        <dl class="dl-horizontal">
          <dt>High school:</dt>
          <dd><%= @education_background.high_school %></dd>

          <dt>English program:</dt>
          <dd><%= @education_background.english_program %></dd>

          <dt>Degree program:</dt>
          <dd><%= @education_background.degree_program %></dd>

          <dt>University:</dt>
          <dd><%= @education_background.university %></dd>

          <dt>Graduate school:</dt>
          <dd><%= @education_background.graduate_school %></dd>

          <dt>Type of degree:</dt>
          <dd><%= @education_background.type_of_degree %></dd>

          <dt>Desired major:</dt>
          <dd><%= @education_background.desired_major %></dd>

          <dt>Student:</dt>
          <dd><%= @education_background.student %></dd>

        </dl>

        </div>
      </div>
    </div>
  </div>
</div>